name: macOS Build

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      sign:
        description: 'Sign and notarize'
        type: boolean
        default: false

env:
  CSC_NAME: ${{ secrets.CSC_NAME }}
  MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
  MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build (draft, unpacked)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          APPLE_TEAM_ID: false
        run: npm run dist:draft

      - name: Codesign setup for macOS
        if: "(contains(github.event.head_commit.message, '[publish]') || inputs.sign) && env.MACOS_CERTIFICATE != '' && env.MACOS_CERTIFICATE_PWD != ''"
        run: |
          echo ${{ secrets.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p actions build.keychain
          security import certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain

      - name: Build (signed & notarized)
        if: "(contains(github.event.head_commit.message, '[publish]') || inputs.sign) && env.MACOS_CERTIFICATE != '' && env.MACOS_CERTIFICATE_PWD != ''"
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: electron-blink1-toy-${{ runner.os }}
          path: |
            release/*.zip
            release/*.dmg
