name: Windows Build

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      sign:
        description: 'Sign artifacts'
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build (draft, unsigned)
        run: npm run dist:draft

      - name: Sign artifacts
        if: "contains(github.event.head_commit.message, '[publish]') || inputs.sign"
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://wus2.codesigning.azure.net/
          trusted-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERTIFICATE_PROFILE_NAME }}
          files-folder: release/win-unpacked
          files-folder-filter: exe

      - name: Publish
        if: "contains(github.event.head_commit.message, '[publish]') || inputs.sign"
        run: npm run dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: electron-blink1-toy-${{ runner.os }}
          path: |
            release/*.zip
            release/*.exe
